name: agrlinks_app
description: "farmers market and inventrory app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  firebase_storage: ^12.3.7
  lottie: ^3.2.0
  get: ^4.6.6
  flutter_material_design_icons: ^1.1.7447
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  weather: ^3.1.1
  intl: ^0.20.1
  google_generative_ai: ^0.4.6
  url_launcher: ^6.3.1
  material_design_icons_flutter: ^7.0.7296
  dropdown_search: ^5.0.6
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  timeago: ^3.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/